# Generated by Django 2.2.4 on 2019-09-10 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spmanage', '0001_initial'),
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QingGongModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作业名称')),
                ('workingHours', models.CharField(blank=True, max_length=100, verbose_name='工时')),
                ('fee', models.IntegerField(blank=True, verbose_name='人工费')),
                ('remark', models.CharField(blank=True, max_length=100, verbose_name='备注')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '人工费定额',
                'verbose_name_plural': '人工费定额',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='WorkerfeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workdate', models.DateTimeField(auto_now_add=True, verbose_name='检修日期')),
                ('description', models.TextField(blank=True, verbose_name='检修内容')),
                ('sumfee', models.IntegerField(blank=True, verbose_name='人工费总额')),
                ('workinghours', models.CharField(max_length=30, verbose_name='工时')),
                ('fee', models.IntegerField(blank=True, verbose_name='人工单价')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('classid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.ClassModel', verbose_name='班组')),
                ('forgrougid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.GroupModel', verbose_name='服务单位')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='施工人员')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workerfee', models.IntegerField(verbose_name='人工费用')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('outlabid', models.ManyToManyField(to='spmanage.OutlabModel', verbose_name='出库材料')),
                ('workers', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='工作成员')),
                ('workrecordid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devs.WorkRecordsModel', verbose_name='检修单')),
            ],
            options={
                'verbose_name': '结算单',
                'verbose_name_plural': '结算单',
                'ordering': ['crtime'],
            },
        ),
    ]
