# Generated by Django 2.2.4 on 2019-09-10 02:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('addr', models.CharField(blank=True, max_length=50, verbose_name='地址')),
                ('contactname', models.CharField(blank=True, max_length=20, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='联系电话')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '厂家信息',
                'verbose_name_plural': '厂家信息',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='InfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('typenum', models.CharField(blank=True, max_length=50, verbose_name='型号')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('factoryid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spmanage.FactoryModel', verbose_name='厂家')),
            ],
            options={
                'verbose_name': '备件信息',
                'verbose_name_plural': '备件信息',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='InlabModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('unitprice', models.FloatField(blank=True, verbose_name='单价')),
                ('addr', models.CharField(blank=True, max_length=50, verbose_name='存放位置')),
                ('remark', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('infoid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spmanage.InfoModel', verbose_name='备件信息')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='入库人')),
            ],
            options={
                'verbose_name': '入库',
                'verbose_name_plural': '入库',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '备件标签',
                'verbose_name_plural': '备件标签',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '备件分类',
                'verbose_name_plural': '备件分类',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='OutlabModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='数量')),
                ('remark', models.CharField(blank=True, max_length=50, verbose_name='备注')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('inlabid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='spmanage.InlabModel', verbose_name='入库id')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='领取人')),
            ],
            options={
                'verbose_name': '出库',
                'verbose_name_plural': '出库',
                'ordering': ['crtime'],
            },
        ),
        migrations.AddField(
            model_name='infomodel',
            name='tagid',
            field=models.ManyToManyField(blank=True, to='spmanage.TagModel', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='infomodel',
            name='typeid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='spmanage.TypeModel', verbose_name='所属类型'),
        ),
    ]
