# Generated by Django 2.2.4 on 2019-09-18 12:43

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevRecordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='描述')),
                ('level', models.CharField(choices=[('1', '稍后'), ('2', '不重要不紧急'), ('3', '不重要紧急'), ('4', '重要不紧急'), ('5', '重要紧急')], default='1', max_length=2)),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '报修记录',
                'verbose_name_plural': '报修记录',
                'ordering': ['-crtime'],
            },
        ),
        migrations.CreateModel(
            name='DevsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '设备表',
                'verbose_name_plural': '设备表',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='TTModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('bir', models.DateTimeField(verbose_name='出生日期')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '生日',
                'verbose_name_plural': '生日',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecordsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='故障处理描述')),
                ('isfininsh', models.BooleanField(default=False, verbose_name='故障状态')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('devRecordid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devs.DevRecordsModel', verbose_name='设备报修记录id')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='检修人id')),
            ],
            options={
                'verbose_name': '检修记录',
                'verbose_name_plural': '检修记录',
                'ordering': ['-crtime'],
            },
        ),
        migrations.CreateModel(
            name='WorkRecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='设备部位')),
                ('faultDescription', models.TextField(blank=True, null=True, verbose_name='故障描述')),
                ('repairContent', models.TextField(blank=True, null=True, verbose_name='检修内容')),
                ('workType', models.CharField(blank=True, max_length=50, null=True, verbose_name='工作分类')),
                ('faultType', models.CharField(blank=True, max_length=50, null=True, verbose_name='故障分类')),
                ('spareName', models.CharField(blank=True, max_length=50, null=True, verbose_name='备件名称')),
                ('spareType', models.CharField(blank=True, max_length=50, null=True, verbose_name='备件型号')),
                ('spareUnit', models.CharField(blank=True, max_length=50, null=True, verbose_name='备件单位')),
                ('spareQuantity', models.CharField(blank=True, max_length=50, null=True, verbose_name='备件数量')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='故障分析描述')),
                ('isfininsh', models.BooleanField(default=False, verbose_name='故障状态')),
                ('bgTime', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 12, 0), verbose_name='开始时间')),
                ('edTime', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 12, 0), verbose_name='结束时间')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.ClassModel', verbose_name='班组')),
                ('devName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devs.DevsModel', verbose_name='设备名称')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='参与人员')),
                ('recorder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='recorder', to=settings.AUTH_USER_MODEL, verbose_name='录入员')),
            ],
            options={
                'verbose_name': '检修台帐',
                'verbose_name_plural': '检修台帐',
                'ordering': ['-crtime'],
            },
        ),
        migrations.CreateModel(
            name='WorklineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.GroupModel', verbose_name='所属车间')),
            ],
            options={
                'verbose_name': '生产线',
                'verbose_name_plural': '生产线',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='MainmanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('devsid', models.ManyToManyField(blank=True, to='devs.DevsModel', verbose_name='包机设备')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '包机表',
                'verbose_name_plural': '包机表',
                'ordering': ['crtime'],
            },
        ),
        migrations.AddField(
            model_name='devsmodel',
            name='worklineid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devs.WorklineModel', verbose_name='所属生产线'),
        ),
        migrations.AddField(
            model_name='devrecordsmodel',
            name='devsid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='devs.DevsModel', verbose_name='故障设备id'),
        ),
        migrations.AddField(
            model_name='devrecordsmodel',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='报修人id'),
        ),
    ]
