# Generated by Django 2.2.4 on 2019-08-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officemodel',
            name='classid',
        ),
        migrations.RemoveField(
            model_name='officemodel',
            name='groupid',
        ),
        migrations.RemoveField(
            model_name='officemodel',
            name='uid',
        ),
        migrations.DeleteModel(
            name='ClassModel',
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
        migrations.DeleteModel(
            name='officeModel',
        ),
    ]
