# Generated by Django 2.2.4 on 2019-09-09 08:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkRecModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devPart', models.CharField(blank=True, max_length=50, verbose_name='设备部位')),
                ('faultDescription', models.CharField(blank=True, max_length=200, verbose_name='故障描述')),
                ('repairContent', models.CharField(blank=True, max_length=200, verbose_name='检修内容')),
                ('workType', models.CharField(blank=True, max_length=50, verbose_name='工作分类')),
                ('faultType', models.CharField(blank=True, max_length=50, verbose_name='故障分类')),
                ('spareName', models.CharField(blank=True, max_length=50, verbose_name='备件名称')),
                ('spareType', models.CharField(blank=True, max_length=50, verbose_name='备件型号')),
                ('spareUnit', models.CharField(blank=True, max_length=50, verbose_name='备件单位')),
                ('spareQuantity', models.CharField(blank=True, max_length=50, verbose_name='备件数量')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='故障分析描述')),
                ('isfininsh', models.BooleanField(default=False, verbose_name='故障状态')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('devName', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devs.DevsModel', verbose_name='设备名称')),
                ('participants', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='参与人员')),
            ],
            options={
                'verbose_name': '检修台帐',
                'verbose_name_plural': '检修台帐',
                'ordering': ['-crtime'],
            },
        ),
    ]
