# Generated by Django 2.2.5 on 2019-09-18 19:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TTModel',
        ),
        migrations.AlterField(
            model_name='workrecmodel',
            name='faultDescription',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='故障描述'),
        ),
        migrations.AlterField(
            model_name='workrecmodel',
            name='repairContent',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='检修内容'),
        ),
    ]
