# Generated by Django 2.2.4 on 2019-08-12 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('humanres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devs', '0002_auto_20190812_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '设备表',
                'verbose_name_plural': '设备表',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='WorklineModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.GroupModel', verbose_name='所属车间')),
            ],
            options={
                'verbose_name': '生产线',
                'verbose_name_plural': '生产线',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='MainmanModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('devsid', models.ManyToManyField(blank=True, to='devs.DevsModel', verbose_name='包机设备')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '包机表',
                'verbose_name_plural': '包机表',
                'ordering': ['crtime'],
            },
        ),
        migrations.AddField(
            model_name='devsmodel',
            name='worklineid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devs.WorklineModel', verbose_name='所属生产线'),
        ),
    ]
