# Generated by Django 2.2.4 on 2019-08-13 07:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devs', '0004_devrecordsmodel_workrecordsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devrecordsmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='workrecordsmodel',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='故障处理描述'),
        ),
    ]
