# Generated by Django 2.2.4 on 2019-08-12 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '班组表',
                'verbose_name_plural': '班组表',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '部门表',
                'verbose_name_plural': '部门表',
                'ordering': ['crtime'],
            },
        ),
        migrations.CreateModel(
            name='officeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('crtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('uptime', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('classid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.ClassModel', verbose_name='所属班组')),
                ('groupid', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.GroupModel', verbose_name='所属部门')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'verbose_name': '职务表',
                'verbose_name_plural': '职务表',
                'ordering': ['crtime'],
            },
        ),
        migrations.AddField(
            model_name='classmodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='humanres.GroupModel', verbose_name='所属部门'),
        ),
    ]
